# Generated by Django 3.1.1 on 2020-09-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
