# Generated by Django 2.2.8 on 2020-09-16 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_acctive',
            new_name='is_staff',
        ),
    ]
